name: Build & Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v16
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile add nixpkgs#devenv

      - run: devenv shell pnpm run build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/web-printer.user.js
          generate_release_notes: true
